#:kivy 2.3.0
#:import Factory kivy.factory.Factory

<WaitBar@Widget>:
    canvas:
        Color:
            rgba: 1, 0, 0, 1
        Rectangle:
            pos: (10, 10)
            size: (30, 30)

<MyPopup@Popup>:
    title: 'My awesome popup'
    size_hint: (0.9, 0.5)
    RelativeLayout:
        WaitBar:

RootWidget:
    Button:
        text: 'This is a button'
        size_hint: (0.9, 0.5)
        on_release: Factory.MyPopup().open()
